name: Test on pull request

on:
    [pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: set up python
              uses: actions/setup-python@v4
              with:
                python-version: "3.8"

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install .[test]
            
            - name: Run unit tests
              run: |
                pytest test/unit -v
            
            - name: Run static tests
              run: |
                pytest test/static -v

            